apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-guesser
  labels:
    app: number-guesser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: number-guesser
  template:
    metadata:
      labels:
        app: number-guesser
    spec:
      containers:
      - name: number-guesser
        image: tuheen27/end-to-end-devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
