apiVersion: v1
kind: Service
metadata:
  name: number-guesser-service # The name of the Service
spec:
  # The selector must match the labels of the pods created by the Deployment
  selector:
    app: number-guesser

  # Define how the service exposes the application
  ports:
    - protocol: TCP
      port: 80 # The port the Service will be available on
      targetPort: 5000 # The port on the container that the Service will forward traffic to

  # Type of the service. LoadBalancer makes it accessible from outside the cluster.
  type: LoadBalancer
  loadBalancerIP:  203.0.113.100